version: "3.9"
services:
  app:
    image: comptworks/lab:gallery-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prod
      - MONGO_URL=mongodb://mongo:27017/gallery-service
      - PORT=3000
    networks:
      - application
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - application

networks:
  application:

volumes:
  mongodb_data:
