apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-nodeport
  name: app-nodeport-svc
spec:
  ports:
  - nodePort: 30163
    port: 80
    targetPort: 3000
  selector:
    app: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: comptworks/lab:gallery-service
          ports: 
            - containerPort: 3000
          env: 
            - name: MONGO_URL
              value: mongodb://mongo-clusterip-svc.default:27018/gallery-service
            - name: NODE_ENV
              value: prod
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-registry-secret
