apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: comptworks/lab:gallery-service
          ports: 
            - containerPort: 8080
          env: 
            - name: MONGODB_URL
              value: mongodb://mongo:27017/gallery-service
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-registry-secret
