apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyOXRjSFIzYjNKcmN6cFNNMXBXVm5BNVdVZDFaak00TjJFPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson