apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteOnce 
  volumeName: pv001
  resources:
    requests:
      storage: 1Gi